In [1]:
import tensorflow as tf

In [2]:
d0 = tf.ones((1,))

In [3]:
d1 = tf.ones((2,))

In [4]:
d2 = tf.ones((2,2))

In [5]:
d3 = tf.ones((2,2,2))

In [6]:
print(d1.numpy())

[1. 1.]


In [7]:
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [8]:
print(d2.numpy())

[[1. 1.]
 [1. 1.]]


In [9]:
con1 = tf.constant(3)

In [10]:
con1 = tf.constant(3,shape=(2,2))

In [11]:
con2 = tf.constant([1,2,3,4],shape=(2,2))

In [12]:
tf.ones_like(d3)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [13]:
tf.ones_like(con1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [14]:
con1.numpy()

array([[3, 3],
       [3, 3]])

In [15]:
v1 = tf.Variable([1,2,3,4,5],dtype=tf.float32)
v2 = tf.Variable([1,2,3,4,5],dtype=tf.int16)

In [17]:
v1.numpy()

array([1., 2., 3., 4., 5.], dtype=float32)

In [23]:
v1.dtype

tf.float32

In [31]:
con1 = tf.constant(2,tf.float32)

In [32]:
co = tf.multiply(v1,con1)

In [33]:
co.numpy()

array([ 2.,  4.,  6.,  8., 10.], dtype=float32)