In [1]:
import tensorflow as tf

In [22]:
x = tf.Variable(1.0)

In [23]:
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x,x)

In [24]:
g = tape.gradient(y,x)

In [25]:
print(g.numpy())

2.0


In [16]:
img = tf.random.uniform((2,2),maxval=255,dtype=tf.int64)

In [17]:
img.numpy()

array([[ 43,  30],
       [  3, 128]], dtype=int64)

In [20]:
grImg = tf.reshape(img,shape=(2*2,1))

In [21]:
grImg

<tf.Tensor: shape=(4, 1), dtype=int64, numpy=
array([[ 43],
       [ 30],
       [  3],
       [128]], dtype=int64)>